server:
  port: 9003

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/shubh7pandey/config-server-repo
          clone-on-start: true
